root_dir: "C:/Users/conceptD"

gt_folder: "ground_truth"
output_dir: "model_comparison_results"

threshold: 0.65
save_excel: true

models:
  - name: "MobileNetV3-Large"
    log_path: "mobilenet_training_log_augmented.jsonl"
    heatmap_folder: "gradcam_MOBILENET_augmented_infected_predictions"

  - name: "ResNet50"
    log_path: "resnet50_training_log_augmented.jsonl"
    heatmap_folder: "gradcam_RESNET50_augmented_infected_predictions"

  - name: "ResNet18"
    log_path: "resnet18_training_log_augmented.jsonl"
    heatmap_folder: "gradcam_RESNET18_augmented_infected_predictions"

  - name: "ViT-B16"
    log_path: "vit_training_log_augmented.jsonl"
    heatmap_folder: "gradcam_VIT_augmented_infected_predictions"

  - name: "Swin-Tiny"
    log_path: "swin_tiny_training_log_augmented.jsonl"
    heatmap_folder: "gradcam_SWIN_TINY_augmented_infected_predictions"

  - name: "ConvNeXt-Tiny"
    log_path: "convnext_tiny_training_log_augmented.jsonl"
    heatmap_folder: "gradcam_CONVNEXT_TINY_augmented_infected_predictions"

  - name: "ProtoNet-ResNet50"
    log_path: "protonet_resnet50_training_log_augmented.jsonl"
    heatmap_folder: "gradcam_PROTONET_RESNET50_augmented_infected_predictions"

  - name: "ProtoNet-ResNet18"
    log_path: "protonet_resnet18_training_log_augmented.jsonl"
    heatmap_folder: "gradcam_PROTONET_RESNET18_augmented_infected_predictions"

  - name: "ProtoNet-ConvNeXt-Tiny"
    log_path: "protonet_convnext_tiny_training_log_augmented.jsonl"
    heatmap_folder: "gradcam_PROTONET_CONVNEXT_TINY_augmented_infected_predictions"
